name: video_watermark_plus
description: Refurbished Flutter package to add image as overlay in the video along with video trim option.
homepage: https://mahfuzmunna.com/flutter/video_watermark_plus
repository: https://github.com/mahfuzmunna/video_watermark_plus

version: 1.2.0

environment:
  # ✅ Upgraded to the latest stable Dart SDK constraint
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new: ^3.2.0
  path_provider: ^2.1.5

platforms:
  android:
  ios:
